spring.application.name=springboot-backend
spring.datasource.url=jdbc:mysql://localhost:3306/ems?useSSL=false
spring.datasource.username=root
spring.datasource.password=kanha2004



spring.jpa.hibernate.ddl-auto=update